apiVersion: v1
kind: Pod
metadata:
   name: my-pod
   labels:
     app: busybox
spec: 
   containers:
   - name: busybox
     image: radial/busyboxplus:curl
     command: ['sh', '-c', 'while true; do sleep 3600; done']