apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Recyle
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/output


