apiVersion: v1
kind: Pod
metadata: 
  name: shared-volume
spec:
  containers:
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'while true; do echo Success! >> /output/test.txt; sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /output
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'while true; do cat /input/test.txt; sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /input
  volumes:
  - name: shared-volume
    hostPaths:
      path: /var/test
      