apiVersion: v1
kind: Pod
metadata:
  name: pod-svc-test-new-namespace
  namespace: new-namespace
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command: ['sh', '-c', 'while true; do sleep 10; done']