apiVersion: v1
kind: Pod
metadata:
  name: node-pod
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do echo Success! >> /output/test.txt; sleep 10; done']
    volumeMounts:
      - name: host-volume
        mountPath: /output
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'while true; do cat /input/test.txt; sleep 10; done']
    volumeMounts:
      - name: host-volume
        mountPath: /input
  volumes:
  - name: host-volume
    hostPath:
      path: /var/output
